export enum BluetoothErrorEnum {
  SCAN_ERROR = "scanError",
  NOT_INITIALIZED_ERROR = "notInitializedError",
  PERMISSION_ERROR = "permissionError",
  POWER_ON_ERROR = "powerOnError",
  WRITING_ERROR = "writingError",
  READING_ERROR = "readingError",
  CONNECTING_ERROR = "connectingError",
  CONNECTION_ERROR = "connectionError",
  DISCONNECTING_ERROR = "disconnectingError",
  STOP_MEASUREMENT_ERROR = "stopMeasurementError",
  START_MEASUREMENT_ERROR = "startMeasurementError",
  DETECTOR_SETUP_ERROR = "detectorSetupError",
  MEASUREMENT_ERROR = "measurementError",
}
