export enum BluetoothCommandEnum {
  START_MEASUREMENT = 0,
  STOP_MEASUREMENT = 1,
  ENABLE_LIDAR = 2,
  DISABLE_LIDAR = 3,
  ENABLE_LUNA = 4,
  DISABLE_LUNA = 5,
  ENABLE_ULTRASONIC_DETECTORS = 6,
  DISABLE_ULTRASONIC_DETECTORS = 7,
  MEASUREMENT = 8,
}
