export enum ScreenNamesEnum {
  INITIAL_LOADING = "initialLoading",
  INITIAL = "initial",
  SETTINGS = "settings",
  CONNECTION_METHOD_SELECT = "ConnectionMethodSelect",
  BLUETOOTH_SCAN_INIT = "bluetoothScanInit",
  BLUETOOTH_SCAN_RESULTS = "bluetoothScanResults",
  BLUETOOTH_CONNECTION_ATTEMPT = "bluetoothConnectionAttemptScreen",
  WIFI_SEARCH_INIT = "wiFiSearchInit",
  WIFI_SEARCH_RESULTS = "wiFiSearchResults",
  WIFI_CONNECTION_ATTEMPT = "wiFiConnectionAttemptScreen",
  DETECTORS_SETUP = "detectorsSetupScreen",
  DETECTORS_GROUP_DETAILS = "detectorsGroupDetailsScreen",
  ADD_EDIT_DETECTOR_SCREEN = "addEditDetectorScreen",
  CONTROLLER = "controllerScreen",
  MEASUREMENT = "measurementScreen",
}
